execute: main.cpp WindowFeature.h WindowFeature.cpp HOG.h HOG.cpp LBP.cpp LBP.h ImageWindowIterator.h ImageWindowIterator.cpp HistogramBinning.cpp HistogramBinning.h BinaryPatterns.cpp BinaryPatterns.h
	clang++ WindowFeature.cpp HOG.cpp LBP.cpp ImageWindowIterator.cpp main.cpp HistogramBinning.cpp BinaryPatterns.cpp -o execute
