execute: main.cpp WindowFeature.h WindowFeature.cpp HOG.h HOG.cpp LBP.cpp LBP.h ImageWindowIterator.h ImageWindowIterator.cpp GeneralizedHistogramBinning.cpp GeneralizedHistogramBinning.h GeneralizedBinaryPatterns.cpp GeneralizedBinaryPatterns.h
	clang++ WindowFeature.cpp HOG.cpp LBP.cpp ImageWindowIterator.cpp main.cpp GeneralizedHistogramBinning.cpp GeneralizedBinaryPatterns.cpp -o execute
