package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.1,<1.10
    - cython 0.22.*

  run:
    - python
    - pathlib 1.0  # [py2k]

    # Scientific Python Stack
    - numpy >=1.9.1,<1.10
    - scipy 0.15.*
    - matplotlib 1.4.*
    - pillow  2.8.*
    - cyvlfeat 0.3*

    # Convenience dependencies (not strictly required)
    - mock
    - nose
    - ipython-notebook 3.*

test:
  requires:
  - coverage

  imports:
  - menpo

about:
  home: https://github.com/menpo/menpo/
  license: BSD
